#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$CURRENT_BRANCH" = "main" ]; then
  echo "Running E2E tests for 'main' branch..."
  npm run test:e2e
  EXIT_CODE=$?
  if [ $EXIT_CODE -ne 0 ]; then
    echo "E2E tests failed. Push to 'main' aborted."
    exit 1
  fi
else
  echo "Skipping pre-push hook for branch '$CURRENT_BRANCH'."
fi

exit 0
